{
 "title": "Docker Hub Rate Limits",
 "description": "Dockerhub rate limit dashboard for drl-exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerhub_limit_max_requests_total - on() dockerhub_limit_remaining_requests_total",
     "legendFormat": "Used requests"
    },
    {
     "expr": "dockerhub_limit_remaining_requests_total",
     "legendFormat": "Remaining requests"
    },
    {
     "expr": "dockerhub_limit_max_requests_total",
     "legendFormat": "Max requests"
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerhub_limit_remaining_requests_time / 3600",
     "legendFormat": "Remaining Time"
    }
   ]
  },
  {
   "title": "Max Time",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerhub_limit_max_requests_time / 3600",
     "legendFormat": "Max Time"
    }
   ]
  },
  {
   "title": "Used Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dockerhub_limit_max_requests_total - on() dockerhub_limit_remaining_requests_total"
    }
   ]
  },
  {
   "title": "Remaining Requests",
   "type": "graph",
   "description": "Remaining Requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dockerhub_limit_remaining_requests_total",
     "legendFormat": "Remaining requests"
    },
    {
     "expr": "dockerhub_limit_max_requests_total",
     "legendFormat": "Max requests"
    }
   ]
  }
 ]
}